[package]
name = "rust-minesweeper"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.80"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
rand = "0.8.5"